# Generated by Django 4.2.9 on 2024-10-10 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customer',
            name='annual_income',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'employed'), ('self-employed', 'self-employed'), ('unemployed', 'unemployed')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('MONEY_MARKET', 'Money Market'), ('CD', 'Certificate of Deposit (CD)')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='ssn',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('MONEY_MARKET', 'Money Market'), ('CD', 'Certificate of Deposit (CD)')], max_length=20),
        ),
    ]
